# Site settings
title: Aarón Ojeda's personal site
description: Aarón Ojeda's personal site
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Aarón Ojeda
user_description: Self-motivated, analytical and creative software engineer. One way or another, I have been linked to video games professionally, personally or academically during my whole life. Needless to say, I love them. My thesis was about 2D platformers development with C++ and SDL. Leaving aside video games, I have experience in data science and a strong knowledge on basketball.
user_title: Game Developer
email: aaron.ojeda.reyes@gmail.com
# twitter_username: lorem_ipsum
github_username:  afrosistema
# gplus_username:  lorem_ipsum
linkedin_username: aaojeda

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
